### PR TITLE
adds stack allocation for registration function()

### PR DESCRIPTION
**Pull request by giacomodabisias**
adds stack allocation for registration function()

### CODE REVIEW

**Comment by giacomodabisias** [comment]
I will work now on the Cmake file to fix the find libfreenect2 issue

**Comment by giacomodabisias** [comment]
fixed possibility to open kinect2 by serial

**Comment by larshg** [comment]
Looks great - sorry for the slow response, but I'm busy at work atm. I'll try to add the Cmake required for windows users :)

**Comment by giacomodabisias** [comment]
Thanks,
let's see if we are missing anything else. I think at the end when everything is fine we need to fix the code for the police style, but that is quick

**Comment by giacomodabisias** [comment]
HI,
any news?

**Pull request merged**
